name: daily_flow_test
on:
  schedule:
    # run once daily at 12 AM UTC, 8 PM EST
    - cron: '0 0 * * *'

jobs:
  # runs through all the tasks listed in conjur-quickstart daily
  # ensures that the quickstart flow is not broken for end users

  setup-conjur-env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Worlflow Test Script
        run: ./test_workflow.sh
